### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by RobertMakeev07** [andrewwang84/94Orig#10]
Exactly, that's my website link. But you can test, it is not working I don't know why. I have tried too much but in vain. It's working in localhost ports like 3000, but in server nope. I only made bot work fine via your website link by providing that in config vars in Heroku but actually in code it is mine.

You did some changes here, so that's the reason that Bot doesn't work. Both my web and bot are not working now, I made bot work using your link. I suggest discussing this problem closer. 

[Here is my Telegram](https://t.me/robmakeev)

**Comment by andrewwang84** [comment]
Of course your bot work fine via my website link, cause my bot is always working fine online.

And YES I did some changes, for better logging, better twitter support, better response format for telegram, try to improve puppeteer performance...... 
But after these changes, my bot is still working fine and online, so something might went wrong during your deploy to heroku.

Maybe try a manual deploy instead of clicking on the "Try it on HEROKU" button, I admit didn't put too much effort on that button so it might be buggy

**Comment by RobertMakeev07** [comment]
Okay, appreciate, if you give me your Telegram Bot Link.

**Comment by andrewwang84** [comment]
@orig_bot
